class SwapManager:
    def __init__(self, strategy_name: str) -> None: ...
    def _get_balances(self) -> dict: ...
    def _update_balances(self) -> None: ...
    def _get_quote(self, in_address: str, out_address: str, amount: int, slippage_bps: int) -> dict: ...
    def _get_swap_tx(self, quote: dict, priority_fee_max_lamports: int, priority_level: str) -> dict: ...
    def _send_via_jito(self, signed_tx_b64: str) -> str: ...
    def _execute_swap(self, in_address: str, out_address: str, in_amount: int) -> tuple[str, float, int]: ...
    def await_balance_change(self, max_attempts: int = 60, interval: float = 0.5) -> None: ...
    def _optimistic_update(self, in_mint: str, out_mint: str, in_ui_amount: float, out_ui_amount: float, out_decimals: int) -> None: ...
    def swap_in(self, usd_amount: float) -> None: ...
    def swap_out(self, token_amount: float) -> None: ...
