class AdvancedYieldGuardController:
    def __init__(self, strategy_name: str) -> None: ...
    def _check_take_profit(self) -> bool: ...
    def _rebalance_positions(self, hedge_amount_new: float) -> None: ...
    def monitor_positions(self) -> None: ...
