from typing import Optional

from lp_module.ev import EVSnapshot
from lp_module.fee_rate import FeeRateSnapshot, FeeRateTracker
from lp_module.fpt import FPTSnapshot
from lp_module.il import ILSnapshot
from lp_module.volatility import EWMAVolatilityEstimator


class AdvancedYieldGuardController:
    def __init__(self, strategy_name: str) -> None: ...

    def _warm_fee_rate_from_db(self) -> None: ...
    def _mark_position_closed(self) -> None: ...

    def _update_fee_rate(self) -> FeeRateSnapshot: ...
    def _update_volatility(self) -> Optional[float]: ...
    def _update_il(self, current_price: float) -> Optional[ILSnapshot]: ...
    def _update_fpt(
        self,
        current_price: float,
        lower: float,
        upper: float,
        sigma_per_minute: Optional[float],
    ) -> FPTSnapshot: ...
    def _update_ev(
        self,
        current_price: float,
        price_lower: float,
        price_upper: float,
    ) -> EVSnapshot: ...
    def _update_net_pnl(self) -> tuple[Optional[float], Optional[float]]: ...

    def _rebalance_positions(self, hedge_amount_new: float) -> None: ...
    def monitor_positions(self) -> None: ...
