class YieldGuardController:
    def __init__(self, strategy_name: str) -> None: ...
    def _calculate_wallet_equity(self, all_tokens: bool = False) -> tuple[float, dict]: ...
    def get_position_state(self, full_wallet_scan: bool = False, include_advanced: bool = False): ...
    def ensure_balanced(self, mode: str) -> bool: ...
    def open_positions(self) -> bool: ...
    def close_positions(self) -> bool: ...
