class DatabaseHandler:
    def __init__(self) -> None: ...
    def _init_database(self) -> None: ...
    def insert_tracking_record(self, record_data: dict) -> int: ...
    def get_tracking_history(self, limit: int = 100): ...
    def clear_database(self) -> None: ...
