from datetime import datetime
from typing import Optional

from lp_module.ev import EVSnapshot


class TrackingManager:
    def __init__(self) -> None: ...

    def get_active_position(self, strategy_name: str): ...
    def mark_position_closed(self, position_mint: str) -> None: ...

    def hydrate_static(self, position_info) -> None: ...
    def ensure_static(self, lp_manager, hedge_manager, strategy_name: str) -> None: ...

    def record_tick(
        self,
        lp_manager,
        hedge_manager,
        rebalance_diff: float,
        rebalance_trigger_flag: bool,
        ev_snapshot: Optional[EVSnapshot] = None,
        net_pnl_usd: Optional[float] = None,
        net_pnl_ema_usd: Optional[float] = None,
    ) -> int: ...

    def get_recent_fee_samples(self, position_mint: str, since_ts: datetime): ...
    def get_last_fee_rate_ema(self, position_mint: str) -> Optional[float]: ...

    def get_tracking_history(self, limit: int = 100): ...
    def clear_database(self) -> None: ...
