class TrackingManager:
    def __init__(self) -> None: ...
    def record_state(self, lp_manager, hedge_manager, strategy_name: str, rebalance_diff: float, rebalance_trigger_flag: bool) -> int: ...
    def get_tracking_history(self, limit: int = 100): ...
    def clear_database(self) -> None: ...
