class LPManager:
    def __init__(self, strategy_name: str) -> None: ...
    def get_pool_static_info(self) -> None: ...
    def get_pool_dynamic_info(self): ...
    def get_position_static_info(self): ...
    def get_position_dynamic_info(self): ...
    def get_hedge_amount(self) -> float: ...
    def get_lp_fees_usd(self) -> float: ...
    def close_position(self, slippage_bps: int = None) -> str: ...
