from typing import Optional


class EWMAVolatilityEstimator:
    def __init__(self, lambda_: float = 0.94) -> None: ...

    @property
    def sigma_per_minute(self) -> Optional[float]: ...

    def reset(self) -> None: ...
    def get_sigma_per_minute(self, force: bool = False) -> Optional[float]: ...
