class HedgeManager:
    def __init__(self, strategy_name: str) -> None: ...
    def update_position(self, include_advanced: bool = False) -> None: ...
    def update_hedge_equity(self) -> None: ...
    def open_hedge_position(self, size: float) -> None: ...
    def adjust_hedge_position(self, new_size: float) -> None: ...
    def close_hedge_position(self) -> None: ...
